Model test
hideotty/chat-space pull request #8
Opened 2017-08-26 00:52 UTC by hideotty

# What

2017-08-26 02:14 UTC, offich requested changes
お時間よろしいときに、修正していただければ、幸いです。

2017-08-26 02:14 UTC, r-ume commented on .rspec
> +--format documentation
`require spec_helper` もお願いいたします。

2017-08-26 02:14 UTC, r-ume commented on app/controllers/messages_controller.rb
> +    # binding.pry
削除をお願いいたします。

2017-08-26 02:14 UTC, r-ume commented on app/controllers/messages_controller.rb
> +      redirect_to group_messages_path(params[:group_id]), notice: "メッセージを投稿しました"
**THINK**
`params([:group_id])` はなくても大丈夫だと思われます。

2017-08-26 02:14 UTC, r-ume commented on app/models/message.rb
> +    content.present? || img.present?
こちらは、 validatesのあとに書くものなので、 `presence` とお願いいたします。

2017-08-26 02:14 UTC, r-ume commented on spec/factories/user.rb
> +
`password_confirmation` カラムの追加もお願いいたします。

2017-08-26 02:14 UTC, r-ume commented on spec/models/message_spec.rb
> +          message = build(:message, img:'')
**THINK**
こちらだと、 `content` が入っておりませんので、修正の方をお願いいたします。

2017-08-26 02:14 UTC, r-ume commented on spec/models/message_spec.rb
> +          message = build(:message, content:'')
**THINK**
こちらだと、 image が入っておりませんので、修正の方をお願いいたします。

2017-08-26 02:14 UTC, r-ume commented on spec/models/message_spec.rb
> +          message = build(:message)
**THINK**
こちらだと、`content` も `image` も入っていないので、修正の方をお願いいたします。

2017-08-26 02:16 UTC, r-ume commented
細かい部分ですが、コミットメッセージは、全て何を編集したか、具体的に書きましょう。

1. あとで、バグが出てきて、修正するときに、コミットメッセージで編集履歴をたどることができるからです。
2. (@hideotty さんがエンジニア転職されると仮定して、話せていただきます。) 自分がIT企業のエンジニアで、面接でこのchatspaceを見たときに、今のプルリクエストやコミットメッセージだとあまり良い印象を感じないです。なぜなら、一緒に働いても、不明確なプルリクエストをレビューしないといけないと思うからです。コードやプルリクエストを見る人の気持ちになって考えて、なるべくプルリクエストやコミットメッセージは具体的に書きましょう。

2017-08-28 03:38 UTC, takeru56 commented on .rspec
> +require spec_helper
`--color` もデフォルトであった気がするので追記お願いします

2017-08-28 03:38 UTC, takeru56 commented on app/controllers/messages_controller.rb
>      @groups = Group.all
@groupは、indexとcreateで被っているので、private以下でメソッド化した上でbefore_actionを用いて呼び出すようにしましょう。

2017-08-28 04:12 UTC, merged